/**
 * Block-Friendly Python Transpiler
 *
 * Converts Python code (generated by Blockly's pythonGenerator) back into
 * Blockly JSON so blocks and Python views stay in sync.
 *
 * Design principle: each Python pattern maps 1:1 to the custom block type
 * that generated it. Only the patterns that the blocks actually produce are
 * handled – unknown lines become comment blocks rather than being silently
 * dropped.
 */

import { getLibraryBlockForPython } from '../libraryManager';

// Block types that are "structural" (library defs, class defs) — never wrapped in on_start
const STRUCTURAL_TYPES = new Set([
    'structure_module_def', 'structure_typed_function', 'class_define', 'structure_import',
    'class_constructor', 'class_method',
]);

// Hat block types that already have their own container role
const HAT_TYPES = new Set(['loop_forever', 'on_start', 'on_forever', 'when_flag_clicked']);

export const pythonToBlockly = (pythonCode, options = {}) => {
    const { wrapRunnable = false } = options;
    const lines = pythonCode.split('\n');
    const variables = new Set();

    // ── Argument splitter (respects quoted strings) ─────────────────────────
    const splitArgs = (argsStr) => {
        const parts = [];
        let current = '';
        let inString = false;
        let stringChar = '';
        for (let i = 0; i < argsStr.length; i++) {
            const ch = argsStr[i];
            if (inString) {
                current += ch;
                if (ch === stringChar) inString = false;
            } else if (ch === '"' || ch === "'") {
                inString = true;
                stringChar = ch;
                current += ch;
            } else if (ch === ',') {
                parts.push(current.trim());
                current = '';
            } else {
                current += ch;
            }
        }
        if (current.trim()) parts.push(current.trim());
        return parts;
    };

    // ── Value helpers ───────────────────────────────────────────────────────
    const parseValueInput = (val) => {
        val = val.trim();
        if (!val) return null;
        if ((val.startsWith('"') && val.endsWith('"')) ||
            (val.startsWith("'") && val.endsWith("'"))) {
            return { kind: 'block', type: 'text', fields: { TEXT: val.slice(1, -1) } };
        }
        if (!isNaN(val)) {
            return { kind: 'block', type: 'math_number', fields: { NUM: val } };
        }
        if (val === 'True') return { kind: 'block', type: 'logic_boolean', fields: { BOOL: 'TRUE' } };
        if (val === 'False') return { kind: 'block', type: 'logic_boolean', fields: { BOOL: 'FALSE' } };
        if (/^[a-zA-Z_]\w*$/.test(val)) {
            variables.add(val);
            return { kind: 'block', type: 'variables_get', fields: { VAR: { name: val, id: 'var_' + val } } };
        }
        return { kind: 'block', type: 'text', fields: { TEXT: val } };
    };

    // ── Tree builder ────────────────────────────────────────────────────────
    const root = { type: 'root', children: [] };
    let currentParent = root;
    let indentStack = [0];
    let expectingChild = false;

    lines.forEach((line, lineIndex) => {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) return;

        const indent = line.search(/\S/);

        if (expectingChild) {
            if (indent > indentStack[indentStack.length - 1]) {
                indentStack.push(indent);
                expectingChild = false;
            } else {
                expectingChild = false;
                if (currentParent.parent) currentParent = currentParent.parent;
            }
        }

        while (indent < indentStack[indentStack.length - 1]) {
            indentStack.pop();
            if (currentParent.parent) currentParent = currentParent.parent;
        }

        // Helper to push a leaf node (no children expected)
        const leaf = (node) => { currentParent.children.push(node); };
        // Helper to push a container node (children expected on next line)
        const container = (node) => {
            node.parent = currentParent;
            currentParent.children.push(node);
            currentParent = node;
            expectingChild = true;
        };

        // ── Structure blocks ────────────────────────────────────────────────

        // class MyClass(Parent):  or  class MyClass:
        const classMatch = trimmed.match(/^class\s+(\w+)(?:\((\w*)\))?:/);
        if (classMatch) {
            const parent = classMatch[2] || '';
            // Check if this is a module (library) or OOP class by peeking at next lines
            // If we find typed functions (def name(args) -> type:) without 'self', it's a module
            let isModule = false;
            for (let j = lineIndex + 1; j < lines.length; j++) {
                const nextLine = lines[j].trim();
                if (!nextLine || nextLine.startsWith('#')) continue;
                // Stop at next top-level class/def
                if (nextLine.match(/^(class|def)\s+/) && lines[j][0] !== ' ' && lines[j][0] !== '\t') break;
                // Check for typed function without self (module style)
                if (nextLine.match(/^def\s+\w+\([^)]*\)\s*->\s*\w+:/) && !nextLine.includes('self')) {
                    isModule = true;
                    break;
                }
                // If we see __init__ or method with self, it's OOP class
                if (nextLine.match(/^def\s+(__init__|.*\(self)/)) {
                    isModule = false;
                    break;
                }
            }

            if (isModule) {
                container({ type: 'structure_module_def', fields: { NAME: classMatch[1] }, children: [] });
            } else {
                container({ type: 'class_define', fields: { NAME: classMatch[1], PARENT: parent }, children: [] });
            }
            return;
        }

        // def __init__(self, args):
        const ctorMatch = trimmed.match(/^def\s+__init__\(self(?:,\s*(.*))?\):/);
        if (ctorMatch) {
            container({ type: 'class_constructor', fields: { ARGS: (ctorMatch[1] || '').trim() }, children: [] });
            return;
        }

        // def method(self, args) -> ReturnType:
        const methodMatch = trimmed.match(/^def\s+(\w+)\(self(?:,\s*(.*))?\)\s*->\s*(\w+):/);
        if (methodMatch) {
            const typeMap = { void: 'None', boolean: 'bool', string: 'str', number: 'float' };
            const validTypes = ['None', 'int', 'float', 'str', 'bool', 'list', 'dict', 'Any'];
            let rType = typeMap[methodMatch[3]] || methodMatch[3];
            if (!validTypes.includes(rType)) rType = 'Any';
            container({
                type: 'class_method',
                fields: { NAME: methodMatch[1], ARGS: (methodMatch[2] || '').trim(), RETURN_TYPE: rType },
                children: []
            });
            return;
        }

        // def func(args) -> ReturnType:
        const funcMatch = trimmed.match(/^def\s+(\w+)\((.*)\)\s*->\s*(\w+):/);
        if (funcMatch) {
            const typeMap = { void: 'None', boolean: 'bool', string: 'str', number: 'float' };
            const validTypes = ['None', 'int', 'float', 'str', 'bool', 'list', 'dict', 'Any'];
            let rType = typeMap[funcMatch[3]] || funcMatch[3];
            if (!validTypes.includes(rType)) rType = 'Any';
            container({
                type: 'structure_typed_function',
                fields: { NAME: funcMatch[1], ARGS: funcMatch[2], RETURN_TYPE: rType },
                children: []
            });
            return;
        }

        // return value
        const returnMatch = trimmed.match(/^return\s+(.*)/);
        if (returnMatch) {
            const val = returnMatch[1].trim();
            const numVal = !isNaN(val) ? val : '0';
            leaf({
                type: 'structure_return_typed',
                inputs: { VALUE: { block: { kind: 'block', type: 'math_number', fields: { NUM: numVal } } } },
                children: []
            });
            return;
        }

        // import lib — 'import time' is silently ignored (time.sleep → wait block handles it implicitly)
        // Other imports become structure_import blocks for OOP/library code
        const importMatch = trimmed.match(/^import\s+(\w+)/);
        if (importMatch) {
            if (importMatch[1] !== 'time') {
                leaf({ type: 'structure_import', fields: { LIBRARY: importMatch[1] }, children: [] });
            }
            return;
        }

        // ── Motion blocks ───────────────────────────────────────────────────

        // sprite.move(steps)
        const moveMatch = trimmed.match(/^sprite\.move\((-?[\d.]+)\)/);
        if (moveMatch) {
            leaf({ type: 'move_right', fields: { STEPS: moveMatch[1] }, children: [] });
            return;
        }

        // sprite.turn(degrees)  → positive = right, negative = left
        // Note: only 'turn_right' block exists (with DIRECTION dropdown)
        const turnMatch = trimmed.match(/^sprite\.turn\((-?[\d.]+)\)/);
        if (turnMatch) {
            const deg = parseFloat(turnMatch[1]);
            if (deg >= 0) {
                leaf({ type: 'turn_right', fields: { DIRECTION: 'right', DEGREES: String(deg) }, children: [] });
            } else {
                leaf({ type: 'turn_right', fields: { DIRECTION: 'left', DEGREES: String(-deg) }, children: [] });
            }
            return;
        }

        // sprite.set_direction(deg)
        const dirMatch = trimmed.match(/^sprite\.set_direction\((-?[\d.]+)\)/);
        if (dirMatch) {
            leaf({ type: 'point_in_direction', fields: { DEGREES: dirMatch[1] }, children: [] });
            return;
        }

        // sprite.goto(x, y)
        const gotoMatch = trimmed.match(/^sprite\.goto\((-?[\d.]+),\s*(-?[\d.]+)\)/);
        if (gotoMatch) {
            leaf({ type: 'go_to_position', fields: { X: gotoMatch[1], Y: gotoMatch[2] }, children: [] });
            return;
        }

        // sprite.glide(secs, x, y)
        const glideMatch = trimmed.match(/^sprite\.glide\((-?[\d.]+),\s*(-?[\d.]+),\s*(-?[\d.]+)\)/);
        if (glideMatch) {
            leaf({ type: 'glide_to_position', fields: { SECONDS: glideMatch[1], X: glideMatch[2], Y: glideMatch[3] }, children: [] });
            return;
        }

        // sprite.change_x(dx)
        const changeXMatch = trimmed.match(/^sprite\.change_x\((-?[\d.]+)\)/);
        if (changeXMatch) {
            leaf({ type: 'change_x', fields: { DX: changeXMatch[1] }, children: [] });
            return;
        }

        // sprite.change_y(dy)
        const changeYMatch = trimmed.match(/^sprite\.change_y\((-?[\d.]+)\)/);
        if (changeYMatch) {
            leaf({ type: 'change_y', fields: { DY: changeYMatch[1] }, children: [] });
            return;
        }

        // sprite.set_x(x)
        const setXMatch = trimmed.match(/^sprite\.set_x\((-?[\d.]+)\)/);
        if (setXMatch) {
            leaf({ type: 'set_x', fields: { X: setXMatch[1] }, children: [] });
            return;
        }

        // sprite.set_y(y)
        const setYMatch = trimmed.match(/^sprite\.set_y\((-?[\d.]+)\)/);
        if (setYMatch) {
            leaf({ type: 'set_y', fields: { Y: setYMatch[1] }, children: [] });
            return;
        }

        // sprite.if_on_edge_bounce()
        if (trimmed === 'sprite.if_on_edge_bounce()') {
            leaf({ type: 'if_on_edge_bounce', fields: {}, children: [] });
            return;
        }

        // sprite.point_towards("target")
        const pointMatch = trimmed.match(/^sprite\.point_towards\("(.*)"\)/);
        if (pointMatch) {
            leaf({ type: 'point_towards', fields: { TARGET: pointMatch[1] }, children: [] });
            return;
        }

        // ── Looks blocks ────────────────────────────────────────────────────

        // sprite.say(text) or sprite.say(text, seconds)
        const sayMatch = trimmed.match(/^sprite\.say\((.*)\)$/);
        if (sayMatch) {
            const args = splitArgs(sayMatch[1]);
            const textRaw = args[0] || '';
            const inputBlock = parseValueInput(textRaw);
            if (args.length > 1) {
                const sec = args[1].trim();
                leaf({ type: 'say_for_seconds', inputs: { TEXT: { block: inputBlock } }, fields: { SECONDS: sec }, children: [] });
            } else {
                leaf({ type: 'say', inputs: { TEXT: { block: inputBlock } }, fields: {}, children: [] });
            }
            return;
        }

        // sprite.think(text) or sprite.think(text, seconds)
        const thinkMatch = trimmed.match(/^sprite\.think\((.*)\)$/);
        if (thinkMatch) {
            const args = splitArgs(thinkMatch[1]);
            const textRaw = args[0] || '';
            const inputBlock = parseValueInput(textRaw);
            if (args.length > 1) {
                const sec = args[1].trim();
                leaf({ type: 'think_for_seconds', inputs: { TEXT: { block: inputBlock } }, fields: { SECONDS: sec }, children: [] });
            } else {
                leaf({ type: 'think', inputs: { TEXT: { block: inputBlock } }, fields: {}, children: [] });
            }
            return;
        }

        // sprite.switch_costume("name")
        const costumeMatch = trimmed.match(/^sprite\.switch_costume\("(.*)"\)/);
        if (costumeMatch) {
            leaf({ type: 'switch_costume', fields: { COSTUME: costumeMatch[1] }, children: [] });
            return;
        }

        // sprite.next_costume()
        if (trimmed === 'sprite.next_costume()') {
            leaf({ type: 'next_costume', fields: {}, children: [] });
            return;
        }

        // sprite.set_size(n)
        const setSizeMatch = trimmed.match(/^sprite\.set_size\((-?[\d.]+)\)/);
        if (setSizeMatch) {
            leaf({ type: 'set_size', fields: { SIZE: setSizeMatch[1] }, children: [] });
            return;
        }

        // sprite.show()
        if (trimmed === 'sprite.show()') {
            leaf({ type: 'show', fields: {}, children: [] });
            return;
        }

        // sprite.hide()
        if (trimmed === 'sprite.hide()') {
            leaf({ type: 'hide', fields: {}, children: [] });
            return;
        }

        // sprite.play_sound("name")
        const playSoundMatch = trimmed.match(/^sprite\.play_sound\("(.*)"\)/);
        if (playSoundMatch) {
            leaf({ type: 'play_sound', fields: { SOUND: playSoundMatch[1] }, children: [] });
            return;
        }

        // sprite.play_sound_until_done("name")
        const playSoundDoneMatch = trimmed.match(/^sprite\.play_sound_until_done\("(.*)"\)/);
        if (playSoundDoneMatch) {
            leaf({ type: 'play_sound_until_done', fields: { SOUND: playSoundDoneMatch[1] }, children: [] });
            return;
        }

        // sprite.stop_all_sounds()
        if (trimmed === 'sprite.stop_all_sounds()') {
            leaf({ type: 'stop_all_sounds', fields: {}, children: [] });
            return;
        }

        // sprite.set_volume(n)
        const setVolumeMatch = trimmed.match(/^sprite\.set_volume\((-?[\d.]+)\)/);
        if (setVolumeMatch) {
            leaf({ type: 'set_volume', fields: { VOLUME: setVolumeMatch[1] }, children: [] });
            return;
        }

        // sprite.change_volume(n)
        const changeVolumeMatch = trimmed.match(/^sprite\.change_volume\((-?[\d.]+)\)/);
        if (changeVolumeMatch) {
            leaf({ type: 'change_volume', fields: { AMOUNT: changeVolumeMatch[1] }, children: [] });
            return;
        }

        // sprite.change_size(n)
        const changeSizeMatch = trimmed.match(/^sprite\.change_size\((-?[\d.]+)\)/);
        if (changeSizeMatch) {
            leaf({ type: 'change_size', fields: { AMOUNT: changeSizeMatch[1] }, children: [] });
            return;
        }

        // sprite.go_to_layer("front"|"back")
        const goToLayerMatch = trimmed.match(/^sprite\.go_to_layer\("(.*)"\)/);
        if (goToLayerMatch) {
            leaf({ type: 'go_to_layer', fields: { LAYER: goToLayerMatch[1] }, children: [] });
            return;
        }

        // stage.switch_backdrop("name")
        const switchBackdropMatch = trimmed.match(/^stage\.switch_backdrop\("(.*)"\)/);
        if (switchBackdropMatch) {
            leaf({ type: 'switch_backdrop', fields: { BACKDROP: switchBackdropMatch[1] }, children: [] });
            return;
        }

        // stage.next_backdrop()
        if (trimmed === 'stage.next_backdrop()') {
            leaf({ type: 'next_backdrop', fields: {}, children: [] });
            return;
        }

        // sprite.reset_timer()
        if (trimmed === 'sprite.reset_timer()') {
            leaf({ type: 'reset_timer', fields: {}, children: [] });
            return;
        }

        // ── print("msg")
        const printMatch = trimmed.match(/^print\((.*)\)/);
        if (printMatch) {
            const val = printMatch[1].trim();
            const cleanVal = (val.startsWith('"') || val.startsWith("'")) ? val.slice(1, -1) : val;
            leaf({ type: 'print', fields: { TEXT: cleanVal }, children: [] });
            return;
        }

        // ── Control / Loop blocks ───────────────────────────────────────────

        // time.sleep(n)
        const waitMatch = trimmed.match(/^time\.sleep\(([\d.]+)\)/);
        if (waitMatch) {
            leaf({ type: 'wait', fields: { SECONDS: waitMatch[1] }, children: [] });
            return;
        }

        // while True:  → loop_forever
        if (trimmed === 'while True:') {
            container({ type: 'loop_forever', fields: {}, children: [] });
            return;
        }

        // while not(cond):  → repeat_until
        const repeatUntilMatch = trimmed.match(/^while not\((.*)\):/);
        if (repeatUntilMatch) {
            container({ type: 'repeat_until', fields: { CONDITION: repeatUntilMatch[1].trim() }, children: [] });
            return;
        }

        // while cond:  → generic while (repeat_until with negated is complex; map to repeat_until)
        const whileMatch = trimmed.match(/^while\s+(.+):/);
        if (whileMatch) {
            container({ type: 'repeat_until', fields: { CONDITION: whileMatch[1].trim() }, children: [] });
            return;
        }

        // for i in range(n):  → repeat block (n times)
        const forRangeMatch = trimmed.match(/^for\s+(\w+)\s+in\s+range\((\d+)\):/);
        if (forRangeMatch) {
            container({ type: 'repeat', fields: { TIMES: forRangeMatch[2] }, children: [] });
            return;
        }

        // if cond:
        const ifMatch = trimmed.match(/^if\s+(.+):/);
        if (ifMatch) {
            container({ type: 'if', fields: { CONDITION: ifMatch[1].trim() }, children: [] });
            return;
        }

        // elif cond:
        const elifMatch = trimmed.match(/^elif\s+(.+):/);
        if (elifMatch) {
            container({ type: 'custom_elif', fields: {}, inputs: { IF_COND: { block: parseValueInput(elifMatch[1].trim()) } }, children: [] });
            return;
        }

        // else:
        if (trimmed === 'else:') {
            container({ type: 'custom_else', fields: {}, children: [] });
            return;
        }

        // ── Variable blocks ─────────────────────────────────────────────────

        // x += value  → change_variable
        const changeVarMatch = trimmed.match(/^(\w+)\s*\+=\s*(.*)/);
        if (changeVarMatch) {
            leaf({ type: 'change_variable', fields: { VAR_NAME: changeVarMatch[1], VALUE: changeVarMatch[2].trim() }, children: [] });
            return;
        }

        // x = value  → variable (simple assignment)
        const assignMatch = trimmed.match(/^(\w+)\s*=\s*(.*)/);
        if (assignMatch) {
            leaf({ type: 'variable', fields: { VAR_NAME: assignMatch[1], VALUE: assignMatch[2].trim() }, children: [] });
            return;
        }

        // obj.attr = value  → class_property_set
        const propSetMatch = trimmed.match(/^(\w+)\.(\w+)\s*=\s*(.*)/);
        if (propSetMatch && !trimmed.includes('(')) {
            leaf({ type: 'class_property_set', fields: { OBJ: propSetMatch[1], ATTR: propSetMatch[2], VALUE: propSetMatch[3].trim() }, children: [] });
            return;
        }

        // Check installed library reverse patterns BEFORE generic method call
        const libBlock = getLibraryBlockForPython(trimmed);
        if (libBlock) {
            leaf({ type: libBlock.type, fields: libBlock.fields, children: [] });
            return;
        }

        // obj.method(args)  → class_method_call (when obj is a variable, not sprite)
        const methodCallMatch = trimmed.match(/^(\w+)\.(\w+)\((.*)\)/);
        if (methodCallMatch && methodCallMatch[1] !== 'sprite' && methodCallMatch[1] !== 'time') {
            leaf({ type: 'class_method_call', fields: { OBJ: methodCallMatch[1], METHOD: methodCallMatch[2], ARGS: methodCallMatch[3].trim() }, children: [] });
            return;
        }

        // var = ClassName(args)  → class_instance
        const instanceMatch = trimmed.match(/^(\w+)\s*=\s*([A-Z]\w*)\((.*)\)/);
        if (instanceMatch) {
            leaf({ type: 'class_instance', fields: { VAR_NAME: instanceMatch[1], CLASS_NAME: instanceMatch[2], ARGS: instanceMatch[3].trim() }, children: [] });
            return;
        }

        // Generic function call: funcName(args)  → structure_call
        const callMatch = trimmed.match(/^(\w+)\((.*)\)/);
        if (callMatch) {
            const inputBlock = parseValueInput(callMatch[2].trim());
            leaf({
                type: 'structure_call',
                fields: { NAME: callMatch[1] },
                inputs: inputBlock ? { ARG: { block: inputBlock } } : {},
                children: []
            });
            return;
        }

        // pass → skip
        if (trimmed === 'pass') return;

        // Unknown → comment
        leaf({ type: 'comment', fields: { TEXT: trimmed }, children: [] });
    });

    // ── Convert tree to Blockly JSON ────────────────────────────────────────

    const treeToBlock = (node) => {
        const block = {
            kind: 'block',
            type: node.type,
            fields: node.fields || {},
            inputs: node.inputs || {},
            next: null
        };

        // Map block types to the input name that holds their children
        const childInputMap = {
            structure_module_def: 'CONTENT',
            structure_typed_function: 'STACK',
            class_define: 'BODY',
            class_constructor: 'BODY',
            class_method: 'BODY',
            if: 'DO',
            if_else: 'DO',
            custom_elif: 'BODY',
            custom_else: 'BODY',
            repeat_until: 'DO',
            loop_forever: 'DO',
            repeat: 'DO',
            controls_whileUntil: 'DO',
            controls_for: 'DO',
            controls_if: 'DO0',
        };

        const childInputName = childInputMap[node.type];
        if (childInputName && node.children && node.children.length > 0) {
            const firstChild = treeToBlock(node.children[0]);
            let cur = firstChild;
            for (let i = 1; i < node.children.length; i++) {
                const next = treeToBlock(node.children[i]);
                cur.next = { block: next };
                cur = next;
            }
            block.inputs[childInputName] = { block: firstChild };
        }
        return block;
    };

    // ── Build top-level block list ──────────────────────────────────────────

    const codeBlocks = [];
    let lastBlock = null;

    const isSeparator = (type) =>
        type === 'structure_module_def' || type === 'structure_typed_function' ||
        type === 'class_define' || type === 'structure_import' ||
        type === 'class_instance' || type === 'class_method_call';

    root.children.forEach((child) => {
        const block = treeToBlock(child);

        // Merge elif/else into preceding if block
        if (block.type === 'custom_elif' || block.type === 'custom_else') {
            if (lastBlock && lastBlock.type === 'if') {
                // Upgrade to if_else and attach else body
                lastBlock.type = 'if_else';
                lastBlock.inputs['ELSE'] = block.inputs.BODY || {};
            }
            return;
        }

        const newStack = isSeparator(block.type) || !lastBlock || isSeparator(lastBlock.type);
        if (newStack) {
            codeBlocks.push(block);
            lastBlock = block;
        } else {
            lastBlock.next = { block };
            lastBlock = block;
        }
    });

    // ── Optional: wrap runnable top-level chains in on_start ───────────────
    let finalBlocks = codeBlocks;
    if (wrapRunnable) {
        const runnableBlocks = [];
        const structuralBlocks = [];

        codeBlocks.forEach(block => {
            if (STRUCTURAL_TYPES.has(block.type) || HAT_TYPES.has(block.type)) {
                structuralBlocks.push(block);
            } else {
                runnableBlocks.push(block);
            }
        });

        if (runnableBlocks.length > 0) {
            // Chain all runnable blocks together and wrap in on_start
            let head = runnableBlocks[0];
            let tail = head;
            // find tail of chain
            while (tail.next) tail = tail.next.block;
            for (let i = 1; i < runnableBlocks.length; i++) {
                tail.next = { block: runnableBlocks[i] };
                tail = runnableBlocks[i];
                while (tail.next) tail = tail.next.block;
            }
            const onStartBlock = {
                kind: 'block',
                type: 'on_start',
                fields: {},
                inputs: { DO: { block: head } },
                next: null,
            };
            // Imports / classes / typed functions always sit ABOVE on_start
            // so the workspace reads top-down: imports → definitions → runnable code
            const imports = structuralBlocks.filter(b => b.type === 'structure_import');
            const defs    = structuralBlocks.filter(b => b.type !== 'structure_import');
            finalBlocks = [...imports, ...defs, onStartBlock];
        } else {
            // No runnable code — still keep imports first
            const imports = structuralBlocks.filter(b => b.type === 'structure_import');
            const defs    = structuralBlocks.filter(b => b.type !== 'structure_import');
            finalBlocks = [...imports, ...defs];
        }
    }

    // Simple auto-layout
    let currentY = 50;
    finalBlocks.forEach((block) => {
        block.x = 50;
        block.y = currentY;
        currentY += 300;
    });

    return {
        blocks: { blocks: finalBlocks },
        variables: Array.from(variables).map((name) => ({ name, id: 'var_' + name }))
    };
};
